### PR TITLE
fix npm re-download

### PR DESCRIPTION
**Pull request by buwon**
Added a copy of the npm folder. #214

### CODE REVIEW

**Comment by hayd** [comment]
Thanks! Is the gen/ directory no longer there?

**Comment by buwon** [comment]
Line 238 and line 240 are the same.

**Comment by pjroth** [comment]
I tested only the change in https://github.com/hayd/deno-lambda/pull/217/commits/076fe2aa6c7e9daf2011d085d227cfb1bec46d4c and it worked for me (no longer re-downloads on first lambda execution).

Thanks for this!

**Comment by buwon** [comment]
I get a permission error on deno.lock.
```
error: Read-only file system (os error 30)
```
It does not re-download, but it seems to overwrite deno.lock.
I have to copy deno.lock under /tmp.
I followed the README, but what is the problem?

**Comment by osak** [comment]
Any updates on this?

**Comment by luistio** [comment]
any update on this one?

**Comment by buwon** [comment]
Sorry.
I'm not sure how deno works.
This method does not seem to be a clear solution.

**Pull request closed without merging**
